Finished new UI by adding missing Components (not Settings screen yet)
informatik-ag-ngl/envoy pull request #39
Opened 2020-08-24 20:02 UTC by DieGurke

* Implemented new ContactSearch UI
* Implemented new GroupCreation UI
* Removed Alerts
* Managed offline problems

fixes #36

2020-08-24 20:22 UTC, delvh commented
Even without reviewing I already have two points of criticism:
Firstly, your branch is literally titled f/*finishing*_new_UI. And yet you explicitly claim *without SettingsScene*...
Secondly I remind you that in the previous branch you agreed to change all CSS classes and ids from camel Case to hyphen(-)-separated case. As far as I have watched your commits, you haven't done that yet.

2020-08-24 21:21 UTC, DieGurke commented
> Even without reviewing I already have two points of criticism:
> Firstly, your branch is literally titled f/ *finishing* _new_UI. And yet you explicitly claim *without SettingsScene*...
> Secondly, I remind you that in the previous branch you agreed to change all CSS classes and ids from camel Case to hyphen(-)-separated case. As far as I have watched your commits, you haven't done that yet.

Yo chill if you wish so I'll do it tomorrow (but setting screen should be a new branch)

2020-08-24 21:57 UTC, delvh requested changes
Well yes, overall it looks fine, but also yes, there are improvement proposals I have.

(Oh, and I think it would fit to this branch if you remove the rotateButton in ChatScene as we now have the `SystemCommand`s to fulfill that duty)

2020-08-24 21:59 UTC, delvh commented on client/src/main/java/envoy/client/event/LoadGroupCreationEvent.java
> + * Created: <strong>Aug 23, 2020</strong><br>
And also, please add a Javadoc description to that event.
Even after reviewing your PR, I still have no idea what its purppose is...

2020-08-26 12:37 UTC, DieGurke commented on client/src/main/java/envoy/client/event/BackEvent.java
> +
I would not remove the constructor

2020-08-26 12:39 UTC, DieGurke commented on client/src/main/resources/css/base.css
> +    -fx-padding: -20 0 0 0;
No this is right this way because the - 20 removes a blank space

2020-08-26 12:39 UTC, DieGurke commented on client/src/main/java/envoy/client/ui/controller/GroupCreationTab.java
> +	private void textUpdated() { createButton.setDisable(userList.getSelectionModel().isEmpty() || groupNameField.getText().isBlank()); }
I totally agree

2020-08-26 12:40 UTC, DieGurke commented on client/src/main/java/envoy/client/ui/controller/GroupCreationTab.java
> +			groupNameField.clear();
yes indeed

2020-08-26 12:59 UTC, delvh commented on client/src/main/java/envoy/client/event/BackEvent.java
> +
It is literally unnecessary. That is the purpose of `Event.Valueless`.

Look at any other Event extending Event.Valueless.

2020-08-26 13:03 UTC, DieGurke commented on client/src/main/java/envoy/client/ui/controller/ChatScene.java
> +					groupCreationTab.setContent(FXMLLoader.load(new File("src/main/resources/fxml/GroupCreationTab.fxml").toURI().toURL()));
Well see, I am aware of the possibility of using relative paths as you have mentioned in your first point. Secondly, `FXMLLoader` is a static class and therefore must not me instanced and so you can save 2 extra lines of code. I am using an URL to first load the file and the feeding it to the `FXMLLoader` as this is the only way to load the files without getting several errors. (Trust me I tried everything). And lastly I see your point but loading the files `SceneContext` is not working as we would have to define a base location referencing the file and due to the architecture we are using, this isn't an easy task. (Base location isn't explicitly defined as it changes dynamically and this is resulting in problems when loading the tabs). Next I don't see the necessity of defining a `tabContext` as it is much easier and nicer to lead the tabs directly inside the place where they get embedded later. (First I tried `fx:include` inside the `ChatScene` FXML file but it didn't work, so the current solution is the only one working ans pretty short ontop. :)

2020-08-26 13:07 UTC, DieGurke commented on client/src/main/java/envoy/client/ui/controller/ChatScene.java
> +				groupCreationTab.setContent(createOfflineNote());
I understand your intention but I think letting the user know why he is denied access is a bit more user friedly.

2020-08-26 13:09 UTC, DieGurke commented on client/src/main/java/envoy/client/ui/controller/ChatScene.java
> +					e2.printStackTrace();
I used `Level.SEVERE` as it is a very severe error, when parts of the application can't be loaded. :)

2020-08-26 13:17 UTC, delvh commented on client/src/main/java/envoy/client/ui/controller/ChatScene.java
> +				groupCreationTab.setContent(createOfflineNote());
Then add an fx:id to the HBox in line 55 (`ChatScene.fxml`), disable it and add a Tooltip to it if offline.
The code looks something like this:
`@FXML`
`private HBox hBox; `
`private Tooltip onlyIfOnlineTooltip = new Tooltip(text);`
...
`if(online)Tooltip.install(hbox, onlyIfOnlineTooltip)`
`else Tooltip.uninstall(hbox, onlyIfOnlineTooltip);`
`hBox.setDisable(!online)`

2020-08-26 13:30 UTC, CyB3RC0nN0R commented on client/src/main/java/envoy/client/event/BackEvent.java
> +
This constructur is not compliant with our style guidelines (redundant code), so please remove it.

2020-08-26 13:43 UTC, delvh requested changes
Overall better.

I still have to say that using tabs is brilliant (I didn't know about them), however I'm pretty confident that the current implementation can be improved.

2020-08-26 13:43 UTC, delvh commented on client/src/main/java/envoy/client/event/BackEvent.java
> + * This event serves the purpose to trigger the tab change to tab 1 in {@link ChatScene}.<p>
```suggestion
 * This event serves the purpose to trigger the tab change to tab 0 in {@link ChatScene}.<p>
```

2020-08-26 13:43 UTC, delvh commented on client/src/main/java/envoy/client/event/LoadGroupCreationEvent.java
> + * It is triggered as soon as the corresponding button in {@link ChatScene} is clicked. <p>
If that is what it is used for, why don't we just use a similar mechanism as used in ChatScene (calling initializeData from the parent(= ChatScene))?

2020-08-26 13:43 UTC, delvh commented on client/src/main/java/envoy/client/ui/controller/ChatScene.java
> +					e2.printStackTrace();
```suggestion
```

2020-08-26 13:43 UTC, delvh commented on client/src/main/java/envoy/client/ui/controller/ChatScene.java
> +					e2.printStackTrace();
Fine.

2020-08-26 13:43 UTC, delvh commented on client/src/main/java/envoy/client/ui/controller/ChatScene.java
> +
```suggestion
```

2020-08-26 13:43 UTC, delvh commented on client/src/main/java/envoy/client/ui/controller/ChatScene.java
> +		eventBus.dispatch(new LoadGroupCreationEvent(localDB));
See as mentioned at `LoadGroupCreationEvent`

2020-08-26 13:43 UTC, delvh commented on client/src/main/java/envoy/client/ui/controller/GroupCreationTab.java
> +			setErrorMessageLabelSize(0);
```suggestion
			eventBus.dispatch(new BackEvent());
			// Restoring the original design as tabs will always be reused
			setErrorMessageLabelSize(0);
```

2020-08-26 13:43 UTC, delvh commented on client/src/main/java/envoy/client/ui/controller/GroupCreationTab.java
> +		errorProceedBox.setMaxHeight(value);
If I'm not completely wrong, it should also be possible to just set `VGrow` and `HGrow` of those elements to `Priority.NEVER` in the method `initialize` and then just changing the preferred size.

2020-08-26 13:43 UTC, delvh commented on client/src/main/resources/fxml/ChatScene.fxml
> -						<Button id="roundButton" fx:id="rotateButton" minWidth="40.0" mnemonicParsing="false" onAction="#doABarrelRoll" prefHeight="40.0" prefWidth="40.0">
While you did delete the button in `ChatScene`, you can even delete the method `@FXML doABarrelRoll()` entirely. The version used by the system command uses the one with two parameters

2020-08-26 15:19 UTC, DieGurke commented on server/install-debian-dev.sh
> +#!/bin/sh
I don't know. I asked that to myself as well.

2020-08-26 15:21 UTC, DieGurke commented on client/src/main/java/envoy/client/event/LoadGroupCreationEvent.java
> + * It is triggered as soon as the corresponding button in {@link ChatScene} is clicked. <p>
We don't have a reference to the tab controller in ChatScene as it gets created by the FXMLLoader internally.

2020-08-26 15:55 UTC, delvh commented on client/src/main/java/envoy/client/event/LoadGroupCreationEvent.java
> + * It is triggered as soon as the corresponding button in {@link ChatScene} is clicked. <p>
Have you ever had a look at the implementation in SceneContext? The method used there can be applied here to, which is what I was already saying, that the loading should be centralized in either `SceneContext` or a similar class.

2020-08-27 12:21 UTC, delvh approved these changes
Now it is getting really good.

The only complaints I now have are on convention and language, which means I ran out of things to complain on the technical side.
(In my case, that's a compliment. I'm a true Swabian when it comes to complimenting.)

2020-08-27 12:21 UTC, delvh commented on client/src/main/java/envoy/client/ui/controller/ChatScene.java
> +					logger.log(Level.SEVERE, "An error occured when attempting to load the tabs!", e2);
```suggestion
					logger.log(Level.SEVERE, "An error occurred when attempting to load tabs: ", e2);
```

2020-08-27 12:21 UTC, delvh commented on client/src/main/resources/css/light.css
Isn't the default text color black?
I'd suppose that this is unnecessary.
```suggestion
```

2020-08-27 12:21 UTC, delvh commented on client/src/main/resources/css/light.css
> +	-fx-background-color: #8fa88f;
I like it if we use only one method of hexadecimal: either all CAPS or all lowercase. Given that almost every other element is in CAPS (at least in this file), I'd suggest:
```suggestion
	-fx-background-color: #8FA88F;
```

2020-08-27 12:21 UTC, delvh commented on client/src/main/resources/css/dark.css
>  	-fx-text-fill: rgb(105.0,0.0,153.0);
I've noticed that we use several different methods of declaring colors in dark.css.

Maybe we could **later on, not now,** unify them as it is somewhat confusing to see colors on multiple occasions declared as `rgb(...)`, then in hexadec CAPS notation (`#F12AED` for example) and then again in hexadec lowercase notation (`#f12aed` for example).

(And **why does GitHub automatically display colors???**)

2020-08-27 18:19 UTC, DieGurke commented on client/src/main/resources/css/light.css
Could be, but I would like to keep it as it is good for clarity.

2020-08-27 19:33 UTC, delvh commented on client/src/main/resources/css/light.css
I do not think that it is making the code much clearer. Who'll ever take a look back at these lines? The only times I'm looking at them is when I'm changing them. And that is an operation that is rather impactful on the overall speed of Envoy as it will be applied to **every single** node that uses these CSS files. That accumulates over time.
So, in my opinion this makes the code not clearer AND is wasting time. Hence it is unnecessary.
I wonder what @CyB3RC0nN0R thinks about that.

2020-08-27 19:53 UTC, CyB3RC0nN0R approved these changes
I really appreciate this implementation as it makes the application much cleaner both for the user and on the code side of things 👍

2020-08-27 19:53 UTC, CyB3RC0nN0R commented on client/src/main/java/envoy/client/ui/controller/ChatScene.java
> +				} catch (Exception e2) {
As this is an exception that can only occur in development, we might consider wrapping it as a `RuntimeException` instead.

```suggestion
				} catch (IOException e2) {
```

2020-08-27 19:53 UTC, CyB3RC0nN0R commented on client/src/main/java/envoy/client/ui/controller/ChatScene.java
> +		tabPane.getSelectionModel().select(1);
Can we introduce some kind of constant for this? Code like this is very susceptible to changes in the tab order and hard to understand once some time has passed.

2020-08-27 19:53 UTC, CyB3RC0nN0R commented on client/src/main/java/envoy/client/ui/controller/GroupCreationTab.java
```suggestion
```

2020-08-27 19:53 UTC, CyB3RC0nN0R commented on client/src/main/java/envoy/client/ui/controller/GroupCreationTab.java
> +		createButton.setDisable(false);
I see a considerable amount of code duplication inside this method and the one below it. Maybe you can extract the duplicate code to a helper method.

2020-08-27 19:53 UTC, CyB3RC0nN0R commented on client/src/main/java/envoy/client/ui/controller/GroupCreationTab.java
> +		errorProceedBox.setMaxHeight(value);
Yes, please.

2020-08-27 19:53 UTC, CyB3RC0nN0R commented on client/src/main/resources/css/dark.css
>  	-fx-text-fill: rgb(105.0,0.0,153.0);
Maybe we can settle on RGB notation, as it is the one used inside Java code as well?

2020-08-27 19:53 UTC, CyB3RC0nN0R commented on client/src/main/resources/css/light.css
Explicitly setting the color to black implies that it is something different by default, which can be misleading. In this case I agree with @delvh and urge you to remove the statement for the sake of clarity.

2020-08-27 21:43 UTC, delvh commented on client/src/main/resources/css/dark.css
>  	-fx-text-fill: rgb(105.0,0.0,153.0);
While it is used inside Java code, most of the CSS files are written right now in caps hexadec notation.
In the end I don't care, it should just be uniform.

2020-08-29 08:58 UTC, DieGurke commented on client/src/main/resources/css/dark.css
>  	-fx-text-fill: rgb(105.0,0.0,153.0);
I would use hexadec as it is smaller

2020-08-29 09:20 UTC, DieGurke commented on client/src/main/java/envoy/client/ui/controller/GroupCreationTab.java
> +		errorProceedBox.setMaxHeight(value);
I am sorry to disappoint you guys, but it does not work. I tried and despite hGrow and vGrow set to never, setting min and max size of the elements is crucial as the elements don't get displayed if those variables are not set.

2020-08-29 15:38 UTC, CyB3RC0nN0R approved these changes

2020-08-29 19:11 UTC, delvh reviewed
While most requests have now been merged, a few remain unsolved so far. Are these supposed to be considered later on (in another PR)?

I'm conflicted on whether to approve in such a case. How strict are we following through with the `branches have to be complete before merging` rule?

Furthermore, please merge develop into this branch at some time. Before that, any approval will automatically be invalided, I assume.

2020-08-30 13:37 UTC, DieGurke commented
This is the final version of this PR so please review now (I think this is a bug: It says that there are conflicts, but they can't be resolved and there aren't any of there conflicts)

2020-08-30 13:51 UTC, DieGurke commented
This is the final version of this PR so please review now

2020-08-30 17:31 UTC, delvh submitted a review, later dismissed
Good.

2020-08-30 17:31 UTC, delvh commented on client/src/main/java/envoy/constant/Tabs.java
> +	public static int CONTANCT_LIST = 0;
Please refactor this constant to `CONTACT_LIST`.

2020-08-30 18:00 UTC, delvh approved these changes
:+1:

2020-08-31 06:08 UTC, CyB3RC0nN0R approved these changes

2020-08-31 06:10 UTC, merged